set( NAME core )
set( VERSION 0.1 )
set( TYPE LIBRARY )
set( DEPENDENCIES  )
set( REQUIREMENTS  )
set( WARNINGS_AS_ERRORS ON )
set( GENERATE_OBJECT_LIB ON) # Needed forDetailTest (generates_obj target)
