set( NAME fwServicesTest )
set( VERSION  )
set( TYPE TEST )
set( DEPENDENCIES fwCore fwTest fwTools fwRuntime fwData fwServices fwCom fwThread )
set( REQUIREMENTS dataReg servicesReg )
set( WARNINGS_AS_ERRORS ON )
