set( NAME fwServicesTest )
set( VERSION  )
set( TYPE TEST )
set( DEPENDENCIES core fwTest fwTools fwRuntime fwData fwServices fwCom )
set( REQUIREMENTS fwData servicesReg )
set( WARNINGS_AS_ERRORS ON )
