
set( NAME arucoMarker )
set( VERSION 0.1 )
set( TYPE EXECUTABLE )
set( OPTIONS CONSOLE TRUE )
set( DEPENDENCIES )
set( REQUIREMENTS )

set( CONAN_DEPS
    ${CONAN_BOOST}
    ${CONAN_OPENCV}
    ${CONAN_FFMPEG}
    ${CONAN_QT}
)
