add_definitions(
    -DBOOST_ALL_DYN_LINK
    -DBOOST_THREAD_DONT_PROVIDE_DEPRECATED_FEATURES_SINCE_V3_0_0
    -DBOOST_THREAD_PROVIDES_FUTURE
    -DBOOST_THREAD_VERSION=2
    -DBOOST_SPIRIT_USE_PHOENIX_V3
)
